name: file_helper
description: some file helper method
version: 0.0.2
homepage: https://github.com/xiaoliang-cn/flutter_file_helper

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: